#!/usr/bin/env python3

brew_applications = [
    "bash",
    "broot",
    "cmake",
    "emacs",
    "git",
    "groff",
    "neofetch",
    "npm",
    "nushell",
    "perl",
    "pipenv",
    "python",
    "python3",
    "tokei",
    "tree",
    "yarn",
    "zig",
]

brew_cask_applications = [
    "android-studio",
    "atom",
    "blender",
    "cutter",
    "cyberduck",
    "db-browser-for-sqlite",
    "discord",
    "dropbox",
    "duet",
    "emacs",
    "firefox",
    "fork",
    "github",
    "go2shell",
    "google-chrome",
    "intellij-idea-ce",
    "licecap",
    "mactex",
    "malwarebytes",
    "microsoft-excel",
    "microsoft-powerpoint",
    "microsoft-teams",
    "microsoft-word",
    "pycharm-ce",
    "reaper",
    "slack",
    "sourcetree",
    "steam",
    "sublime-merge",
    "ti-connect-ce",
    "unity",
    "visual-studio-code",
]

pip_applications = [
    "bpython",
    "virtualenv",
]
